# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='spread',
            field=models.FloatField(blank=True),
        ),
    ]
