# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20170903_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tick',
            options={'verbose_name': 'Tick', 'verbose_name_plural': 'Ticks'},
        ),
        migrations.AlterField(
            model_name='tick',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
